 # enable the shutdown endpoint from web (otherwise it is only available from the JMX console)
 endpoints:
  shutdown:
    enabled: true

 info:
  app:
    name: @project.name@
    description: @project.description@
    version: v@project.version@

 logging:
  file: ./game-schedule-pdf-creator.log

 zuul:
  routes:
    clubs:
      path: /clubs
      url: https://api-v2.swissunihockey.ch:443/api
    teams:
      path: /teams
      url: https://api-v2.swissunihockey.ch:443/api